# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
server:
  port: ${random.int[10000,19999]}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dromara@123
    url: jdbc:mysql://82.157.76.80:3306/hertzbeat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    hikari:
      max-lifetime: 120000
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.exmail.qq.com
    username: example@tancloud.cn
    password: example
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true
        debug: false

common:
  queue:
    type: memory
    
warehouse:
  store:
    jpa:
      enabled: false
      expire-time: 1h
    victoria-metrics:
      enabled: true
      url: http://82.157.76.80:8428
      username: root
      password: root
    td-engine:
      enabled: false
      driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
      url: jdbc:TAOS-RS://127.0.0.1:6041/hertzbeat
      username: root
      password: taosdata
    iot-db:
      enabled: false
      host: 127.0.0.1
      rpc-port: 6667
      username: root
      password: root
    redis:
      enabled: false
      host: 127.0.0.1
      port: 6379
      password: 123456
    memory:
      enabled: true
      init-size: 16

scheduler:
  server:
    enabled: true
    port: 1158
