apiVersion: v2
name: hertzbeat
description: An open-source, real-time monitoring system with custom monitoring, high performance cluster and agentless capabilities.
type: application
home: https://hertzbeat.com/
sources:
  - https://github.com/dromara/hertzbeat
  - https://charts.hertzbeat.com
maintainers:
  - name: tom
    email: tomsun28@outlook.com
icon: https://raw.githubusercontent.com/dromara/hertzbeat/master/home/static/img/hertzbeat-logo.png
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.5.0
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v1.5.0"
