# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The monitoring type category：service-application service monitoring db-database monitoring custom-custom monitoring os-operating system monitoring
category: auto
# The monitoring type eg: linux windows tomcat mysql aws...
app: prometheus
# The monitoring i18n name
name:
  zh-CN: Prometheus任务
  en-US: Prometheus Task
# The description and help of this monitoring type
help:
  zh-CN: Prometheus 任务管理，您可以通过此监控支持 Prometheus 协议的应用类型数据，像 Prometheus 监控它们一样方便，并且是可视化页面的操作。<br><span class='help_module_span'>⚠️注意：监控对端需要提供 prometheus metrics 协议的数据接口。</span>
  en-US: Prometheus Task Management, you can use this to monitor application that supports the Prometheus protocol, as convenient as Prometheus monitoring them, and it is a visual page operation. <br><span class='help_module_span'> The monitoring peer needs to provide the data interface of the prometheus metrics protocol. </span>
  zh-TW: Prometheus 任務管理，您可以透過此監控支援 Prometheus 協定的應用程式類型數據，像 Prometheus 監控它們一樣方便，並且是視覺化頁面的操作。 <br><span class='help_module_span'>⚠️注意：監控對端需要提供 prometheus metrics 協定的資料介面。 </span>
helpLink:
  zh-CN: https://hertzbeat.apache.org/zh-cn/docs/help/prometheus/
  en-US: https://hertzbeat.apache.org/docs/help/prometheus/
# Input params define for monitoring(render web ui by the definition)
params:
  # field-param field key
  - field: host
    # name-param field display i18n name
    name:
      zh-CN: 目标Host
      en-US: Target Host
    # type-param field type(most mapping the html input type)
    type: host
    # required-true or false
    required: true
  - field: port
    name:
      zh-CN: 端口
      en-US: Port
    # type-param field type(most mapping the html input type)
    type: number
    # when type is number, range is required
    range: '[0,65535]'
    # default value
    defaultValue: 9091
    required: true
  # field-param field key
  - field: path
    # name-param field display i18n name
    name:
      zh-CN: 端点路径
      en-US: Endpoint Path
    # type-param field type(most mapping the html input type)
    type: text
    # param field input placeholder
    placeholder: 'Exporter Url Endpoint Path'
    defaultValue: "/metrics"
    # required-true or false
    required: true
  - field: timeout
    name:
      zh-CN: 查询超时时间
      en-US: Query Timeout
    type: number
    required: false
    # hide param-true or false
    hide: true
    defaultValue: 6000
  # field-param field key
  - field: ssl
    # name-param field display i18n name
    name:
      zh-CN: 启用HTTPS
      en-US: HTTPS
    # type-param field type(most mapping the html input type)
    type: boolean
    hide: true
    # field-param field key
  - field: headers
    # name-param field display i18n name
    name:
      zh-CN: 请求Headers
      en-US: Headers
    # type-param field type(most mapping the html input type)
    type: key-value
    # required-true or false
    required: false
    hide: true
    # when type is key-value, use keyAlias to config key alias name
    keyAlias: Header Name
    # when type is key-value, use valueAlias to config value alias name
    valueAlias: Header Value
    # field-param field key
  - field: params
    # name-param field display i18n name
    name:
      zh-CN: 查询Params
      en-US: Params
    # type-param field type(most mapping the html input type)
    type: key-value
    # required-true or false
    required: false
    hide: true
    # when type is key-value, use keyAlias to config key alias name
    keyAlias: Param Key
    # when type is key-value, use valueAlias to config value alias name
    valueAlias: Param Value
  # field-param field key
  - field: contentType
    # name-param field display i18n name
    name:
      zh-CN: Content-Type
      en-US: Content-Type
    # type-param field type(most mapping the html input type)
    type: text
    # param field input placeholder
    placeholder: 'Request Body Type'
    # required-true or false
    required: false
    # hide param-true or false
    hide: true
  - field: authType
    # name-param field display i18n name
    name:
      zh-CN: 认证方式
      en-US: Auth Type
    # type-param field type(most mapping the html input type)
    type: radio
    # required-true or false
    required: false
    # hide param-true or false
    hide: true
    # when type is radio checkbox, use option to show optional values {name1:value1,name2:value2}
    options:
      - label: Basic Auth
        value: Basic Auth
      - label: Digest Auth
        value: Digest Auth
    # field-param field key
  - field: username
    # name-param field display i18n name
    name:
      zh-CN: 用户名
      en-US: Username
    # type-param field type(most mapping the html input type)
    type: text
    # when type is text, use limit to limit string length
    limit: 50
    # required-true or false
    required: false
    # hide param-true or false
    hide: true
    # field-param field key
  - field: password
    # name-param field display i18n name
    name:
      zh-CN: 密码
      en-US: Password
    # type-param field type(most mapping the html input type)
    type: password
    # required-true or false
    required: false
    # hide param-true or false
    hide: true
# collect metrics config list
metrics:
  # metrics - cluster_node_status
  - name: auto
    # metrics scheduling priority(0->127)->(high->low), metrics with the same priority will be scheduled in parallel
    # priority 0's metrics is availability metrics, it will be scheduled first, only availability metrics collect success will the scheduling continue
    priority: 0
    # the protocol used for monitoring, eg: sql, ssh, http, telnet, wmi, snmp, sdk
    protocol: prometheus
    # the config content when protocol is http
    prometheus:
      # http host: ipv4 ipv6 domain
      host: ^_^host^_^
      # http port
      port: ^_^port^_^
      # http path
      path: ^_^path^_^
      timeout: ^_^timeout^_^
      # http method: GET POST PUT DELETE PATCH
      method: GET
      # if enabled https
      ssl: ^_^ssl^_^
      # http request payload
      payload: ^_^payload^_^
      # http request header content
      headers:
        content-type: ^_^contentType^_^
        ^_^headers^_^: ^_^headers^_^
      # http request params
      params:
        ^_^params^_^: ^_^params^_^
      # http auth
      authorization:
        # http auth type: Basic Auth, Digest Auth, Bearer Token
        type: ^_^authType^_^
        basicAuthUsername: ^_^username^_^
        basicAuthPassword: ^_^password^_^
        digestAuthUsername: ^_^username^_^
        digestAuthPassword: ^_^password^_^
